export const BEGIN_AJAX_REQUEST = 'BEGIN_AJAX_REQUEST';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const CHANGE_DATE = 'CHANGE_DATE';
export const FILTER_EVENTS = 'FILTER_EVENTS';
